MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Models/AfisareProduse.cs
using MVIM.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MagazinVirtualInstrMuzicale.Models
{
    public class AfisareProduse
    {
        public IEnumerable<Categorie> CategoriiProduse { get; set; }

        public int IdCategorieSelectata { get; set; }

        public List<MVIM.DAL.Produs> ListaProduse { get; set; }
    }
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MagazinVirtualInstrMuzicale.Models
{
    public class User
    {
        public string Username { get; set; }

        public string Email { get; set; }

        public string Nume { get; set; }

        public string Prenume { get; set; }

        public string NumarDeTelefon { get; set; }
    }
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Controllers/Administrator/AdminProduseController.cs
using MagazinVirtualInstrMuzicale.Common;
using MagazinVirtualInstrMuzicale.Models;
using MVIM.DAL;
using MVIM.DAL.DataModels;
using MVIM.Domain.Interfaces;
using MVIM.Domain.Managers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MagazinVirtualInstrMuzicale.Controllers
{
    [AutorizareAdministratorCustom]
    public class AdminProduseController : Controller
    {
        public SesiuneCurenta User = new SesiuneCurenta();
        private IUserManager _userManager = new UserManager();
        private IProdusManager _produsManager = new ProdusManager();
        private IComandaManager _comandaManager = new ComandaManager();
        private static int idProdus;

        //public AdminProduseController(IProdusManager produsManager, IUserManager userManager)
        //{
        //    _produsManager = produsManager;
        //    _userManager = userManager;
        //}


        [HttpGet]
        public ActionResult AdaugaProdus()
        {
            var model = GetAdaugaProdusModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult AdaugaProdus(Models.Produs produsNou, int IdCategorieProdusSelectata, int IdProducatorProdusSelectat)
        {
            byte[] pozaArray;
            using (Stream inputStream = produsNou.Upload.InputStream)
            {
                MemoryStream memoryStream = inputStream as MemoryStream;
                if (memoryStream == null)
                {
                    memoryStream = new MemoryStream();
                    inputStream.CopyTo(memoryStream);
                }
                pozaArray = memoryStream.ToArray();
            }

            var categorieProdus = _produsManager.GetCategorieById(IdCategorieProdusSelectata);


            var isSaved = _produsManager.AdaugaProdus(
                produsNou.Descriere,
                (decimal)produsNou.Pret,
                produsNou.Nume,
                pozaArray,
                IdCategorieProdusSelectata,
                IdProducatorProdusSelectat
                );

            var model = GetAdaugaProdusModel();

            return View(model);
        }


        public ActionResult LoadPicture(int id)
        {
            var bytePhoto = _produsManager.ReturnPhotos(id);
            return File(bytePhoto, "image/png");
        }

        public ActionResult OperatiuniProduse()
        {
            return View();
        }

        public ActionResult AdaugaCategorie()
        {
            var categoriiModel = _produsManager.GetCategorii() as IEnumerable<MVIM.DAL.Categorie>;
            return View(categoriiModel);
        }

        [HttpPost]
        public ActionResult AdaugaCategorie(string numeCategorie)
        {
            _produsManager.AdaugaCategorieNoua(numeCategorie);

            var categoriiModel = _produsManager.GetCategorii() as IEnumerable<MVIM.DAL.Categorie>;

            return PartialView("_categoriiProdusePartialView", categoriiModel);
        }

        public ActionResult EditeazaCategorie(int idCategorie)
        {
            var categorieToEdit = _produsManager.GetCategorieById(idCategorie);
            return View(categorieToEdit);
        }

        [HttpPost]
        public ActionResult EditeazaCategorie(Categorie categorieDeEditat)
        {
            var updateCategorie = _produsManager.ActualizeazaCategorie(categorieDeEditat);
            return RedirectToAction("AdaugaCategorie");
        }

        public ActionResult DeleteCategorie(int idCategorie)
        {
            var esteStearsa = _produsManager.StergeCategorie(idCategorie);
            var categoriiModel = _produsManager.GetCategorii() as IEnumerable<MVIM.DAL.Categorie>;
            if (esteStearsa)
            {
                return PartialView("_categoriiProdusePartialView", categoriiModel);
            }
            return PartialView("_categoriiProdusePartialView", categoriiModel);
        }

        public ActionResult AdaugaProducator()
        {
            var producatoriModel = _produsManager.GetProducatori() as IEnumerable<Producator>;
            return View(producatoriModel);
        }

        [HttpPost]
        public ActionResult AdaugaProducator(string numeProducator)
        {
            _produsManager.AdaugaProducatorNou(numeProducator);
            var producatoriModel = _produsManager.GetProducatori() as IEnumerable<Producator>;

            return PartialView("_producatoriProdusePartialView", producatoriModel);
        }

        public ActionResult DeleteProducator(int idProducator)
        {
            var stergeProducator = _produsManager.StergeProducator(idProducator);
            var producatoriModel = _produsManager.GetProducatori();

            return PartialView("_producatoriProdusePartialView", producatoriModel);
        }

        public ActionResult EditeazaProducator(int idProducator)
        {
            var producatorToEdit = _produsManager.GetProducatorById(idProducator);
            return View(producatorToEdit);
        }

        [HttpPost]
        public ActionResult EditeazaProducator(Producator producatorDeEditat)
        {
            var updateProducator = _produsManager.ActualizeazaProducator(producatorDeEditat);
            return RedirectToAction("AdaugaProducator");
        }

        public ActionResult AfisareProduse()
        {
            var produse = _produsManager.GetProduse();
            return View(produse);
        }

        [HttpGet]
        public ActionResult EditeazaProdus(int id)
        {
            idProdus = id;
            var produsDeEditat = _produsManager.GetProdus(id);
            return View(produsDeEditat);
        }

        [HttpPost]
        public ActionResult EditeazaProdus(MVIM.DAL.Produs produsActualizat)
        {
            var esteActualizat = _produsManager.ActualizeazaProdus(produsActualizat, idProdus);
            if (esteActualizat)
            {
                return RedirectToAction("AfisareProduse");
            }
            return View();
        }

        public ActionResult StergeProdus(int id)
        {
            var aFostSters = _produsManager.StergeProdus(id);
            if (aFostSters)
            {
                return RedirectToAction("AfisareProduse");
            }
            return RedirectToAction("AfisareProduse");
        }

        public ActionResult Users()
        {
            var listaUseri = new List<Models.User>();

            var useri = _userManager.GetUsers();

            foreach (var user in useri)
            {
                var clientForUser = _userManager.GetClientForUsername(user.IdUser);

                listaUseri.Add(
                    new Models.User
                    {
                        Email = clientForUser.Email,
                        NumarDeTelefon = clientForUser.NumarTelefon,
                        Nume = clientForUser.Nume,
                        Prenume = clientForUser.Prenume,
                        Username = user.UserName
                    });
            }
            //TODO: Retrieve users.
            return View(listaUseri);
        }

        public ActionResult Delete(string username)
        {
            var esteSters = _userManager.DeleteUser(username);
            if (esteSters)
            {
                return RedirectToAction("Users");
            }
            else
                return RedirectToAction("Users");
        }

        private AdaugaProdusModel GetAdaugaProdusModel()
        {
            var model = new AdaugaProdusModel();

            model.CategoriiProduse = _produsManager.GetCategorii();
            model.ProducatoriProduse = _produsManager.GetProducatori();

            return model;
        }

        [HttpGet]
        public ActionResult ComenziPlasate()
        {
            var produseComandate = _produsManager.GetProduseComandate();

            return View(produseComandate);
        }

        [HttpGet]
        public ActionResult ExpediazaComanda(int idComanda)
        {
            ModelState.Clear();
            _comandaManager.ExpediazaComanda(idComanda, "Comanda Expediata");

            var produseComandate = _produsManager.GetProduseComandate();
                        
            return PartialView("_comenziPlasatePartialView", produseComandate);
        }

        [HttpGet]
        public ActionResult StergeComanda(int idComanda)
        {
            ModelState.Clear();
            _comandaManager.StergeComanda(idComanda);

            var produseComandate = _produsManager.GetProduseComandate();

            return PartialView("_comenziPlasatePartialView", produseComandate);
        }

        [HttpGet]
        public ActionResult Search(string searchTerm)
        {
            var produseComandate = _produsManager.GetProduseComandate();

            produseComandate.ListaComenzi = produseComandate.ListaComenzi.Where(x => x.StatusComanda.DescriereStatusComanda.ToLower().Contains(searchTerm.ToLower()) ||
                                                                                     x.Client.Nume.ToLower().Contains(searchTerm.ToLower()) ||
                                                                                     x.Client.Prenume.ToLower().Contains(searchTerm.ToLower())).ToList();

            return PartialView("_comenziPlasatePartialView", produseComandate);
        }
    }
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/AdaugaCategorie.cshtml
@model IEnumerable<MVIM.DAL.Categorie>
<h3>Adauga Categorie</h3>

<form method="post" enctype="multipart/form-data">
    Categorie noua:
    <br />
    <input type="text" name="NumeCategorie" id="valueOfCateogieId" />
    <br />
    <input type="button" value="Adauga" id="adaugaCategorieId"/>
    <br />
</form>
<br />
<div id="renderCategoriiPartialView">
    @{ Html.RenderPartial("_categoriiProdusePartialView", Model); }
</div>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/AdaugaProducator.cshtml
@model IEnumerable<MVIM.DAL.Producator>
<h3>Adauga Producator</h3>

<form method="post" enctype="multipart/form-data">
    Adauga producator nou:
    <br />
    <input type="text" id="numeProducatorId" name="NumeProducator" />
    <br />
    <input type="button" id="adaugaProducatorId" value="Adauga" />
    <br />
</form>
<br />
<div id="renderProducatoriPartialView">
    @{ Html.RenderPartial("_producatoriProdusePartialView", Model); }
</div>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/AdaugaProdus.cshtml
@model MagazinVirtualInstrMuzicale.Models.AdaugaProdusModel

<h2>Adauga Produs</h2>

<form method="post" enctype="multipart/form-data">
    Nume Produs:
    <br />
    <input type="text" name="Nume" />
    <br />
    Pret Produs:
    <br />
    <input type="text" name="Pret" />
    <br />
    Descriere Produs:
    <br />
    <textarea type="text" name="Descriere"></textarea>
    <br />
    Categorie Produs:
    <br />
    @Html.DropDownListFor(m => m.IdCategorieProdusSelectata, new SelectList(Model.CategoriiProduse, "IdCategorie", "NumeCategorie"), "  --Selecteaza Categoria--  ")
    <br />
    Producator Produs:
    <br />
    @Html.DropDownListFor(m => m.IdProducatorProdusSelectat, new SelectList(Model.ProducatoriProduse, "IdProducator", "Nume"), "  --Selecteaza Producator--  ")
    <br />
    Incarca Poza:
    <br />
    <input type="file" id="FileId" name="Upload" />
    <br />
    <br />
    <input type="submit" value="Adauga" />
    <br />
</form>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/AfisareProduse.cshtml
@model IEnumerable<MVIM.DAL.Produs>

@{
    ViewBag.Title = "AfisareProduse";
}

<h2>AfisareProduse</h2>
<br />
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                Numele Produsului: @item.NumeProdus
                <br />
                Pretul Produsului:   @item.PretProdus
                <br />
                Poza Produs:
                @foreach (var poza in item.PozaProdus)
                {
                    <div> <img src='/AdminProduse/LoadPicture?id=@poza.IdPozaProdus' width="250" height="100" /></div>
                }
                <br />
            </td>
            <td>
                @Html.ActionLink("Editeaza", "EditeazaProdus", "AdminProduse", new { id = item.IdProdus }, null) |

                @Html.ActionLink("Delete", "StergeProdus", "AdminProduse", new { id = item.IdProdus }, null)
            </td>
        </tr>
    }
</table>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/ComenziPlasate.cshtml
@model MVIM.DAL.DataModels.ComenziPlasateDataModel
<br />
<div style="float:right">
    <input id="searchTrimId" type="text" />&nbsp;<button id="cautaButtonId">Cauta</button>
</div>
<br />
<div id="reloadContentComenziPlasateId"> @{ Html.RenderPartial("_comenziPlasatePartialView", Model); }</div>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/EditeazaCategorie.cshtml
@model MVIM.DAL.Categorie

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categorie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeCategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeCategorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/EditeazaProducator.cshtml
@model MVIM.DAL.Producator

@{
    ViewBag.Title = "EditeazaProducator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditeazaProducator</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producator</h4>
        <hr />
       <div class="form-group">
            @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/EditeazaProdus.cshtml
@model MVIM.DAL.Produs

@{
    ViewBag.Title = "EditeazaProdus";
    
}

<h2>EditeazaProdus</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produs</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NumeProdus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeProdus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeProdus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PretProdus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PretProdus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PretProdus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriereProdus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescriereProdus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescriereProdus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/LoadPicture.cshtml
@{
    ViewBag.Title = "LoadPicture";
}

<h2>LoadPicture</h2>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/OperatiuniProduse.cshtml
<h3>OperatiuniProduse</h3>
<ul>
    <li><a href="/AdminProduse/AdaugaCategorie">Adauga Categorie</a></li>
    <li><a href="/AdminProduse/AdaugaProducator">Adauga Producator</a></li>
    <li><a href="/AdminProduse/AdaugaProdus">Adauga Produs</a></li>
    <li><a href="/AdminProduse/AfisareProduse">Afisare Produse</a></li>
</ul>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/Users.cshtml
@model IEnumerable<MagazinVirtualInstrMuzicale.Models.User>

@{
    ViewBag.Title = "Users";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prenume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumarDeTelefon)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nume)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prenume)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumarDeTelefon)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { username=item.Username })
        </td>
    </tr>
}

</table>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/_categoriiProdusePartialView.cshtml
@model IEnumerable<MVIM.DAL.Categorie>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
               @item.NumeCategorie
            </td>
            <td>
                @Html.ActionLink("Editeaza", "EditeazaCategorie", "AdminProduse", new { idCategorie = item.IdCategorie }, null) |

                <a href="#" class="stergeCategorieClass" id="@item.IdCategorie">Sterge</a>
            </td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/ScriptCategorii.js"></script>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/_comenziPlasatePartialView.cshtml
@model MVIM.DAL.DataModels.ComenziPlasateDataModel

<br />
@foreach (var comenzi in Model.ListaComenzi)
{
    <div id="comenziPlasateId" style="border:2px solid black">
        @{
            <strong> Nume Client: @(comenzi.Client.Nume + " " + comenzi.Client.Prenume) &nbsp; Numar Comanda: @comenzi.IdComanda</strong>
                <br />
            var produsePtComanda = Model.ListaProduseComandate.Where(x => x.IdComanda == comenzi.IdComanda).ToList();
            decimal total = 0;
            foreach (var produs in produsePtComanda)
            {
                <div style="position:relative; left:50px;">@("Produs: " + produs.NumeProdus + " | Pret:" + (produs.PretProdus * produs.Cantitate).ToString("#.##") + " | Cantitate:" + produs.Cantitate + " buc")</div>
                total += (produs.PretProdus * produs.Cantitate);
            }
            <br>
            <strong>TOTAL: @total.ToString("#.##") RON</strong>
                <br>
                <br>
                @: Status Comanda: <strong>@comenzi.StatusComanda.DescriereStatusComanda</strong>
                <br>
                <br>
                <button id="@comenzi.IdComanda" class="comandaExpediataId">Comanda Expediata</button>
                <button id="@comenzi.IdComanda" class="stergeComandaId">Sterge Comanda</button>

                <br>
        }
    </div>
        <br />
            }
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/ScriptComenziPlasate.js"></script>

MagazinVirtualInstrMuzicale/MagazinVirtualInstrMuzicale/Views/AdminProduse/_producatoriProdusePartialView.cshtml
@model IEnumerable<MVIM.DAL.Producator>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nume
            </td>
            <td>
                @Html.ActionLink("Editeaza", "EditeazaProducator", "AdminProduse", new { idProducator = item.IdProducator }, null) |

                <a href="#" class="stergeProducatorClass" id="@item.IdProducator">Sterge</a>
            </td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/ScriptProducatori.js"></script>